'use client';

import { Job, JobRequirement } from './jobs-service';

// Enhanced job data with 40 diverse jobs across different categories
export const enhancedJobData: Job[] = [
  // Education - Primary School Jobs
  {
    id: 1,
    title: 'Primary School Teacher',
    organization: 'London City School',
    location: 'London, UK',
    type: 'Full-time',
    posted: '2023-07-10',
    match: 85,
    salary: '£28,000 - £35,000',
    applicationDeadline: '2023-08-15',
    startDate: 'September 2023',
    description: 'Experienced primary school teacher needed for Year 3 class. Responsibilities include curriculum planning, assessment, and creating an engaging learning environment.',
    aboutOrganization: 'London City School is a vibrant primary school committed to providing a nurturing and stimulating environment where children can thrive academically and personally.',
    responsibilities: [
      'Plan and deliver engaging lessons aligned with the national curriculum',
      'Assess and monitor student progress and provide regular feedback',
      'Create a positive and inclusive classroom environment',
      'Collaborate with colleagues and participate in staff development',
      'Communicate effectively with parents and guardians',
    ],
    requirements: [
      { id: 1, text: 'Bachelor\'s degree in Education', essential: true, met: true },
      { id: 2, text: 'Qualified Teacher Status (QTS)', essential: true, met: true },
      { id: 3, text: 'Minimum 2 years teaching experience', essential: true, met: false },
      { id: 4, text: 'Strong classroom management skills', essential: true, met: true },
      { id: 5, text: 'Experience with assessment for learning', essential: false, met: true },
      { id: 6, text: 'Ability to differentiate instruction', essential: false, met: true },
    ],
    benefits: [
      'Competitive salary package',
      'Continuous professional development opportunities',
      'Supportive work environment',
      'Pension scheme',
      'School holidays',
    ],
    applicationProcess: 'Submit your CV and a cover letter explaining your interest and suitability for the role. Shortlisted candidates will be invited for an interview and a teaching demonstration.',
    category: 'Education',
    skills: ['Classroom Management', 'Curriculum Planning', 'Assessment', 'Communication'],
  },
  {
    id: 2,
    title: 'Early Years Foundation Teacher',
    organization: 'Sunshine Nursery School',
    location: 'Bristol, UK',
    type: 'Full-time',
    posted: '2023-07-12',
    match: 91,
    salary: '£24,000 - £30,000',
    applicationDeadline: '2023-08-20',
    startDate: 'September 2023',
    description: 'Dedicated Early Years teacher needed to create a stimulating learning environment for our youngest students. Focus on play-based learning and early development milestones.',
    aboutOrganization: 'Sunshine Nursery is an Outstanding-rated early years setting focused on providing the best start for children ages 3-5.',
    responsibilities: [
      'Implement the EYFS curriculum through engaging activities',
      'Track individual children\'s development and maintain learning journals',
      'Create a safe, welcoming classroom environment',
      'Build positive relationships with parents and carers',
      'Support children in developing social and emotional skills',
    ],
    requirements: [
      { id: 1, text: 'Early Years Teacher Status or QTS', essential: true, met: true },
      { id: 2, text: 'Experience working with EYFS age group', essential: true, met: true },
      { id: 3, text: 'Knowledge of child development', essential: true, met: true },
      { id: 4, text: 'Safeguarding training', essential: true, met: false },
      { id: 5, text: 'First Aid qualification', essential: false, met: true },
    ],
    benefits: [
      'Competitive salary',
      'Term-time only working pattern',
      'Ongoing professional development',
      'Pension scheme',
      'Supportive team environment',
    ],
    applicationProcess: 'Apply with CV and personal statement. Shortlisted candidates will attend an interview and observe a teaching session.',
    category: 'Education',
    skills: ['Early Years Foundation Stage', 'Child Development', 'Play-based Learning', 'Observation'],
  },
  {
    id: 3,
    title: 'Special Educational Needs Coordinator',
    organization: 'Riverside Academy Trust',
    location: 'Manchester, UK',
    type: 'Full-time',
    posted: '2023-07-15',
    match: 78,
    salary: '£35,000 - £45,000',
    applicationDeadline: '2023-08-31',
    startDate: 'September 2023',
    description: 'Experienced SENCo required to lead special educational needs provision across our primary academies. The ideal candidate will have a thorough understanding of SEND Code of Practice and experience managing intervention programs.',
    aboutOrganization: 'Riverside Academy Trust manages five primary schools across Greater Manchester with a commitment to inclusive education for all children.',
    responsibilities: [
      'Coordinate SEND provision across multiple school sites',
      'Manage the identification and assessment of pupils with SEN',
      'Support teachers in developing differentiated approaches',
      'Liaise with external agencies and specialists',
      'Lead the team of teaching assistants supporting SEND pupils',
    ],
    requirements: [
      { id: 1, text: 'Qualified Teacher Status', essential: true, met: true },
      { id: 2, text: 'National Award for SEN Coordination', essential: true, met: false },
      { id: 3, text: 'Minimum 3 years experience in SEND role', essential: true, met: true },
      { id: 4, text: 'Knowledge of current SEND legislation', essential: true, met: true },
      { id: 5, text: 'Experience with Education Health Care Plans', essential: true, met: true },
      { id: 6, text: 'Management experience', essential: false, met: false },
    ],
    benefits: [
      'Leadership scale salary',
      'Trust-wide professional development',
      'Supportive senior leadership team',
      'Teachers\' pension scheme',
      'Wellbeing support program',
    ],
    applicationProcess: 'Submit application form and letter detailing your experience and approach to SEND leadership. Two-stage interview process with presentation required.',
    category: 'Education',
    skills: ['Special Educational Needs', 'Leadership', 'Intervention Planning', 'Multi-agency Working'],
  },
  {
    id: 4,
    title: 'Primary Literacy Coordinator',
    organization: 'Greenwich Primary Academy',
    location: 'London, UK',
    type: 'Full-time',
    posted: '2023-07-08',
    match: 64,
    salary: '£32,000 - £38,000',
    applicationDeadline: '2023-08-25',
    startDate: 'September 2023',
    description: 'We are seeking an enthusiastic Literacy Coordinator to lead on reading and writing initiatives across our school. The successful candidate will have a passion for children\'s literature and experience implementing effective literacy strategies.',
    aboutOrganization: 'Greenwich Primary Academy is a three-form entry school serving a diverse community with a focus on creative curriculum and high academic standards.',
    responsibilities: [
      'Lead the development of literacy across all key stages',
      'Monitor and evaluate the teaching of reading and writing',
      'Coordinate literacy intervention programs',
      'Organize literacy events and author visits',
      'Support teachers in enhancing their literacy teaching',
    ],
    requirements: [
      { id: 1, text: 'Qualified Teacher Status', essential: true, met: true },
      { id: 2, text: 'Evidence of literacy leadership experience', essential: true, met: false },
      { id: 3, text: 'Knowledge of current literacy teaching approaches', essential: true, met: true },
      { id: 4, text: 'Experience teaching across KS1 and KS2', essential: false, met: true },
      { id: 5, text: 'Evidence of raising literacy standards', essential: true, met: false },
    ],
    benefits: [
      'TLR2 allowance',
      'Support for further professional qualifications',
      'Collaborative team environment',
      'Teachers\' pension scheme',
      'Centrally located school with good transport links',
    ],
    applicationProcess: 'Apply with CV and supporting statement. Shortlisted candidates will teach a demonstration lesson and attend a panel interview.',
    category: 'Education',
    skills: ['Literacy Teaching', 'Curriculum Leadership', 'Phonics', 'Reading Assessment'],
  },
  
  // Education - Secondary School Jobs
  {
    id: 5,
    title: 'Secondary Science Teacher',
    organization: 'Oakridge Academy',
    location: 'Manchester, UK',
    type: 'Full-time',
    posted: '2023-07-05',
    match: 72,
    salary: '£30,000 - £42,000',
    applicationDeadline: '2023-08-10',
    startDate: 'September 2023',
    description: 'Passionate Science teacher needed to teach Biology, Chemistry, and Physics at KS3 and KS4 levels. The ideal candidate will inspire students to develop a love for scientific inquiry.',
    aboutOrganization: 'Oakridge Academy is a high-performing secondary school with excellent facilities for science education, including well-equipped laboratories and a strong STEM focus.',
    responsibilities: [
      'Teach Biology, Chemistry, and Physics at KS3 and KS4 levels',
      'Prepare students for GCSE examinations',
      'Develop and implement engaging practical experiments',
      'Monitor and evaluate student progress',
      'Contribute to the development of the science curriculum',
    ],
    requirements: [
      { id: 1, text: 'Bachelor\'s degree in a Science subject', essential: true, met: true },
      { id: 2, text: 'Qualified Teacher Status (QTS)', essential: true, met: true },
      { id: 3, text: 'Experience teaching all three sciences at KS3 and KS4', essential: true, met: false },
      { id: 4, text: 'Strong practical teaching skills', essential: true, met: true },
      { id: 5, text: 'Experience with GCSE exam preparation', essential: false, met: false },
    ],
    benefits: [
      'Competitive salary based on experience',
      'Extensive professional development opportunities',
      'Modern teaching facilities',
      'Supportive department team',
      'Teachers\' pension scheme',
    ],
    applicationProcess: 'Apply with your CV, cover letter, and the contact details of two professional references. Shortlisted candidates will be invited for an interview, which will include a teaching demonstration.',
    category: 'Education',
    skills: ['Science Education', 'Laboratory Management', 'GCSE Preparation', 'Assessment'],
  },
  {
    id: 6,
    title: 'Head of Mathematics',
    organization: 'King Edward Grammar School',
    location: 'Birmingham, UK',
    type: 'Full-time',
    posted: '2023-07-18',
    match: 88,
    salary: '£45,000 - £55,000',
    applicationDeadline: '2023-08-20',
    startDate: 'September 2023',
    description: 'We are seeking an outstanding Head of Mathematics to lead our successful department. The ideal candidate will be a passionate mathematics teacher with strong leadership skills and a track record of academic excellence.',
    aboutOrganization: 'King Edward Grammar is a selective school with a strong academic tradition. Our mathematics department consistently achieves exceptional results, with over 90% of students securing A*-B grades at A-Level.',
    responsibilities: [
      'Lead and manage the mathematics department',
      'Teach mathematics across KS3, KS4, and KS5',
      'Monitor and improve department performance',
      'Develop innovative teaching strategies',
      'Manage department budget and resources',
    ],
    requirements: [
      { id: 1, text: 'Mathematics degree from a respected university', essential: true, met: true },
      { id: 2, text: 'Qualified Teacher Status', essential: true, met: true },
      { id: 3, text: 'Minimum 5 years teaching experience', essential: true, met: true },
      { id: 4, text: 'Experience teaching Further Mathematics A-Level', essential: true, met: true },
      { id: 5, text: 'Previous leadership experience', essential: true, met: true },
      { id: 6, text: 'Track record of outstanding examination results', essential: false, met: true },
    ],
    benefits: [
      'Leadership scale salary',
      'Reduced teaching timetable',
      'Professional development budget',
      'Supportive senior leadership team',
      'Opportunities to teach the most able students',
    ],
    applicationProcess: 'Submit application with detailed CV and letter. The selection process includes a panel interview, presentation on your vision for the department, and demonstration lesson.',
    category: 'Education',
    skills: ['Mathematics Teaching', 'Department Leadership', 'Curriculum Development', 'Staff Management'],
  },
  {
    id: 7,
    title: 'English Teacher - Sixth Form Specialist',
    organization: 'Hillcrest College',
    location: 'Leeds, UK',
    type: 'Full-time',
    posted: '2023-07-11',
    match: 76,
    salary: '£32,000 - £42,000',
    applicationDeadline: '2023-08-18',
    startDate: 'September 2023',
    description: 'Experienced English teacher required to join our outstanding English department with a focus on A-Level English Literature and Language. The successful candidate will have excellent subject knowledge and a passion for post-16 education.',
    aboutOrganization: 'Hillcrest College is a leading sixth form college with over a thousand students. Our English department is one of our flagship faculties with excellent student outcomes and progression to Russell Group universities.',
    responsibilities: [
      'Teach A-Level English Literature and Language',
      'Support students with university applications',
      'Develop engaging resources for post-16 students',
      'Organize enrichment activities including literary visits',
      'Contribute to the wider English curriculum',
    ],
    requirements: [
      { id: 1, text: 'Degree in English Literature or related subject', essential: true, met: true },
      { id: 2, text: 'Qualified Teacher Status', essential: true, met: true },
      { id: 3, text: 'Experience teaching A-Level English Literature', essential: true, met: false },
      { id: 4, text: 'Knowledge of university application processes', essential: false, met: true },
      { id: 5, text: 'Evidence of helping students achieve high grades', essential: true, met: true },
    ],
    benefits: [
      'Generous holiday allowance',
      'Excellent career progression opportunities',
      'Advanced teaching resources',
      'Academically motivated students',
      'Access to professional development fund',
    ],
    applicationProcess: 'Apply with CV and supporting statement. Interview process includes teaching demonstration with A-Level students and formal interview.',
    category: 'Education',
    skills: ['A-Level English', 'Literary Analysis', 'Post-16 Education', 'Student Mentoring'],
  },
  {
    id: 8,
    title: 'Director of Sixth Form',
    organization: 'St. Margaret\'s Academy',
    location: 'Edinburgh, UK',
    type: 'Full-time',
    posted: '2023-07-01',
    match: 62,
    salary: '£50,000 - £60,000',
    applicationDeadline: '2023-08-15',
    startDate: 'September 2023',
    description: 'Experienced educational leader required to head our thriving Sixth Form. The successful candidate will provide strategic leadership, ensure academic excellence, and support students in their transition to higher education or employment.',
    aboutOrganization: 'St. Margaret\'s Academy is an outstanding school with a large sixth form of 400 students. We have a strong track record of university placements, including Oxbridge and medicine.',
    responsibilities: [
      'Provide strategic leadership for the Sixth Form',
      'Monitor academic standards and implement improvement strategies',
      'Oversee pastoral care and support systems',
      'Manage UCAS applications and careers guidance',
      'Lead a team of sixth form tutors and support staff',
    ],
    requirements: [
      { id: 1, text: 'Qualified Teacher Status', essential: true, met: true },
      { id: 2, text: 'Significant experience in sixth form education', essential: true, met: false },
      { id: 3, text: 'Proven leadership and management experience', essential: true, met: true },
      { id: 4, text: 'Knowledge of university application procedures', essential: true, met: false },
      { id: 5, text: 'Understanding of 16-19 curriculum and funding', essential: true, met: true },
      { id: 6, text: 'Higher degree or leadership qualification', essential: false, met: true },
    ],
    benefits: [
      'Leadership salary scale',
      'Senior leadership team membership',
      'Professional development budget',
      'Potential relocation package',
      'Supportive governing body',
    ],
    applicationProcess: 'Two-stage interview process with presentations, panel interviews, and student panel. Candidates should submit comprehensive CV and vision statement for sixth form education.',
    category: 'Education',
    skills: ['Educational Leadership', 'Sixth Form Management', 'UCAS Process', 'Strategic Planning'],
  },
  
  // Education Support Roles
  {
    id: 9,
    title: 'Teaching Assistant',
    organization: 'Greenfield Primary School',
    location: 'Birmingham, UK',
    type: 'Part-time',
    posted: '2023-07-15',
    match: 90,
    salary: '£18,000 - £22,000 (pro-rata)',
    applicationDeadline: '2023-08-20',
    startDate: 'September 2023',
    description: 'Teaching Assistant needed to support classroom teachers with students aged 5-11. Responsibilities include providing one-on-one support to students, assisting with classroom activities, and supporting the teacher with administrative tasks.',
    aboutOrganization: 'Greenfield Primary School is a friendly and inclusive school with a strong community focus. We pride ourselves on nurturing the whole child and providing a supportive learning environment.',
    responsibilities: [
      'Support students one-on-one and in small groups',
      'Assist the classroom teacher with lesson preparation and delivery',
      'Help create and maintain classroom displays',
      'Support students with diverse learning needs',
      'Assist with classroom organization and record-keeping',
    ],
    requirements: [
      { id: 1, text: 'Level 3 Teaching Assistant qualification', essential: true, met: true },
      { id: 2, text: 'Experience working with primary school children', essential: true, met: true },
      { id: 3, text: 'Good literacy and numeracy skills', essential: true, met: true },
      { id: 4, text: 'First Aid certification', essential: false, met: true },
      { id: 5, text: 'Experience with SEN students', essential: false, met: true },
    ],
    benefits: [
      'School term-time only working',
      'Professional development opportunities',
      'Supportive team environment',
      'Local government pension scheme',
      'Staff wellbeing program',
    ],
    applicationProcess: 'Submit your CV and a personal statement highlighting your relevant experience and skills. Shortlisted candidates will be invited for an interview and a practical assessment.',
    category: 'Education Support',
    skills: ['Student Support', 'Classroom Assistance', 'SEN Support', 'Administrative Support'],
  },
  {
    id: 10,
    title: 'Learning Mentor',
    organization: 'Phoenix Secondary School',
    location: 'Liverpool, UK',
    type: 'Full-time',
    posted: '2023-07-16',
    match: 82,
    salary: '£22,000 - £26,000',
    applicationDeadline: '2023-08-25',
    startDate: 'September 2023',
    description: 'Dedicated Learning Mentor required to support vulnerable students in overcoming barriers to learning. The successful candidate will work with individuals and small groups to improve attendance, behavior, and academic engagement.',
    aboutOrganization: 'Phoenix Secondary serves a diverse urban community with a commitment to ensuring all students achieve their potential regardless of background or challenges.',
    responsibilities: [
      'Provide one-to-one and small group mentoring',
      'Develop strategies to improve student engagement',
      'Liaise with teachers regarding student progress',
      'Work with families to support learning at home',
      'Maintain records of interventions and impact',
    ],
    requirements: [
      { id: 1, text: 'Experience working with young people', essential: true, met: true },
      { id: 2, text: 'Understanding of barriers to learning', essential: true, met: true },
      { id: 3, text: 'Excellent communication skills', essential: true, met: true },
      { id: 4, text: 'Safeguarding knowledge', essential: true, met: true },
      { id: 5, text: 'Mentoring qualification', essential: false, met: false },
      { id: 6, text: 'Experience working in educational settings', essential: false, met: true },
    ],
    benefits: [
      'Term-time only with paid holidays',
      'Ongoing professional development',
      'Supportive team environment',
      'Local government pension scheme',
      'Employee assistance program',
    ],
    applicationProcess: 'Submit CV and covering letter explaining your approach to mentoring. Interview will include practical scenarios and meeting with student panel.',
    category: 'Education Support',
    skills: ['Mentoring', 'Behavior Management', 'Relationship Building', 'Intervention Planning'],
  },
  
  // Physical Education Jobs
  {
    id: 11,
    title: 'Physical Education Teacher',
    organization: 'Westside Secondary School',
    location: 'Liverpool, UK',
    type: 'Full-time',
    posted: '2023-07-08',
    match: 65,
    salary: '£26,000 - £36,000',
    applicationDeadline: '2023-08-05',
    startDate: 'September 2023',
    description: 'PE teacher needed for all key stages. The successful candidate will be responsible for planning and delivering PE lessons, organizing sports events, and promoting physical activity throughout the school.',
    aboutOrganization: 'Westside Secondary School has a strong tradition of sporting excellence and offers outstanding facilities including a sports hall, all-weather pitch, and swimming pool.',
    responsibilities: [
      'Teach PE across all key stages',
      'Coach school sports teams',
      'Organize inter-school competitions and sports days',
      'Promote the importance of physical activity and healthy lifestyles',
      'Assess and track student progress in PE',
    ],
    requirements: [
      { id: 1, text: 'Bachelor\'s degree in Physical Education', essential: true, met: true },
      { id: 2, text: 'Qualified Teacher Status (QTS)', essential: true, met: true },
      { id: 3, text: 'Experience coaching team sports', essential: true, met: false },
      { id: 4, text: 'First Aid certification', essential: true, met: true },
      { id: 5, text: 'Swimming instructor qualification', essential: false, met: false },
    ],
    benefits: [
      'Competitive salary',
      'Excellent sports facilities',
      'Continuous professional development',
      'Pension scheme',
      'Staff wellbeing program',
    ],
    applicationProcess: 'Apply with your CV and cover letter explaining your sports specialties and coaching experience. Shortlisted candidates will be invited for an interview and a practical demonstration.',
    category: 'Physical Education',
    skills: ['Sports Coaching', 'Physical Education', 'Event Organization', 'Team Leadership'],
  },
  {
    id: 12,
    title: 'Head of Athletics',
    organization: 'British Sports Academy',
    location: 'Cardiff, UK',
    type: 'Full-time',
    posted: '2023-07-04',
    match: 94,
    salary: '£38,000 - £48,000',
    applicationDeadline: '2023-08-10',
    startDate: 'September 2023',
    description: 'Experienced athletics coach needed to lead our prestigious athletics program. The successful candidate will be responsible for training elite young athletes, organizing competitions, and developing our athletics curriculum.',
    aboutOrganization: 'British Sports Academy is a specialist sports college with national recognition for developing young athletes who compete at national and international levels.',
    responsibilities: [
      'Develop and implement a comprehensive athletics program',
      'Coach students in track and field events at elite level',
      'Organize internal and external athletics competitions',
      'Talent scout and develop promising young athletes',
      'Liaise with national governing bodies and sports clubs',
    ],
    requirements: [
      { id: 1, text: 'UK Athletics Level 3 or 4 coaching qualification', essential: true, met: true },
      { id: 2, text: 'Proven track record developing elite athletes', essential: true, met: true },
      { id: 3, text: 'Experience organizing athletics competitions', essential: true, met: true },
      { id: 4, text: 'Understanding of athlete development pathways', essential: true, met: true },
      { id: 5, text: 'Personal background in competitive athletics', essential: false, met: true },
    ],
    benefits: [
      'Leadership salary scale',
      'World-class training facilities',
      'Professional development budget',
      'Flexible working hours',
      'Performance-related bonuses',
    ],
    applicationProcess: 'Apply with comprehensive CV detailing coaching achievements. Interview process includes practical coaching assessment and presentation on athletics development strategy.',
    category: 'Physical Education',
    skills: ['Athletics Coaching', 'Competition Organization', 'Talent Development', 'Performance Analysis'],
  },
  
  // Higher Education Jobs
  {
    id: 13,
    title: 'Lecturer in Computer Science',
    organization: 'University of Northern England',
    location: 'Manchester, UK',
    type: 'Full-time',
    posted: '2023-07-12',
    match: 87,
    salary: '£38,000 - £46,000',
    applicationDeadline: '2023-09-15',
    startDate: 'January 2024',
    description: 'We are seeking a passionate Lecturer in Computer Science to join our thriving department. The successful candidate will deliver high-quality teaching in software engineering and contribute to our research in AI and machine learning.',
    aboutOrganization: 'The University of Northern England is a research-intensive institution known for its strong industry connections and innovative teaching approaches in computer science and related fields.',
    responsibilities: [
      'Deliver undergraduate and postgraduate teaching in software engineering',
      'Develop and update curriculum content',
      'Supervise student projects and dissertations',
      'Conduct research in relevant field',
      'Participate in departmental administration',
    ],
    requirements: [
      { id: 1, text: 'PhD in Computer Science or related field', essential: true, met: true },
      { id: 2, text: 'Teaching experience in higher education', essential: true, met: true },
      { id: 3, text: 'Research record with publications', essential: true, met: true },
      { id: 4, text: 'Industry experience in software development', essential: false, met: true },
      { id: 5, text: 'Fellowship of the Higher Education Academy', essential: false, met: false },
    ],
    benefits: [
      'Generous pension scheme',
      'Research and conference allowance',
      'Flexible working options',
      'Generous annual leave',
      'Staff development programs',
    ],
    applicationProcess: 'Submit CV, cover letter, and research statement. Shortlisted candidates will give a teaching demonstration and research presentation followed by a panel interview.',
    category: 'Higher Education',
    skills: ['Computer Science', 'Teaching', 'Research', 'Software Engineering'],
  },
  {
    id: 14,
    title: 'Professor of Economics',
    organization: 'London School of Economics',
    location: 'London, UK',
    type: 'Full-time',
    posted: '2023-07-01',
    match: 75,
    salary: '£65,000 - £90,000',
    applicationDeadline: '2023-10-20',
    startDate: 'February 2024',
    description: 'Distinguished Professor of Economics required to provide academic leadership in research and teaching. The successful candidate will be an internationally recognized scholar with a track record of research funding and publications.',
    aboutOrganization: 'The London School of Economics is a world-leading social science institution with an outstanding reputation for economic research and education.',
    responsibilities: [
      'Lead research initiatives in macroeconomics',
      'Teach specialized courses at undergraduate and graduate levels',
      'Supervise PhD students',
      'Secure research grants and funding',
      'Contribute to department leadership and governance',
    ],
    requirements: [
      { id: 1, text: 'PhD in Economics', essential: true, met: true },
      { id: 2, text: 'International research profile', essential: true, met: true },
      { id: 3, text: 'Track record of publications in top journals', essential: true, met: false },
      { id: 4, text: 'Experience securing research funding', essential: true, met: true },
      { id: 5, text: 'Experience of PhD supervision', essential: true, met: true },
    ],
    benefits: [
      'Professorial salary',
      'Research sabbaticals',
      'Relocation package',
      'Access to research support staff',
      'International conference budget',
    ],
    applicationProcess: 'Applications should include CV, research statement, teaching portfolio, and names of three referees. Shortlisted candidates will give a research presentation and teaching demonstration.',
    category: 'Higher Education',
    skills: ['Economics', 'Research', 'Academic Leadership', 'Grant Writing'],
  },
  {
    id: 15,
    title: 'Student Support Officer',
    organization: 'Sheffield Hallam University',
    location: 'Sheffield, UK',
    type: 'Full-time',
    posted: '2023-07-10',
    match: 79,
    salary: '£28,000 - £32,000',
    applicationDeadline: '2023-08-20',
    startDate: 'September 2023',
    description: 'Student Support Officer needed to provide guidance and assistance to students on a range of welfare, academic, and personal issues. The role involves being a first point of contact for students seeking advice and support.',
    aboutOrganization: 'Sheffield Hallam University is a large public university with a strong focus on student experience and wellbeing, serving over 30,000 students across multiple faculties.',
    responsibilities: [
      'Provide advice and guidance to students on university services',
      'Refer students to appropriate specialist support',
      'Help students navigate academic regulations',
      'Support students in crisis or with complex needs',
      'Deliver workshops on student wellbeing',
    ],
    requirements: [
      { id: 1, text: 'Degree or equivalent experience', essential: true, met: true },
      { id: 2, text: 'Experience in student support or advisory role', essential: true, met: true },
      { id: 3, text: 'Knowledge of higher education sector', essential: true, met: false },
      { id: 4, text: 'Understanding of mental health issues', essential: true, met: true },
      { id: 5, text: 'Counseling qualification', essential: false, met: false },
    ],
    benefits: [
      '35 days annual leave including public holidays',
      'Excellent pension scheme',
      'Flexible working options',
      'Staff development opportunities',
      'Discounted gym membership',
    ],
    applicationProcess: 'Submit CV and personal statement addressing the person specification. Assessment includes interview and case study exercise.',
    category: 'Higher Education',
    skills: ['Student Support', 'Advice & Guidance', 'Crisis Management', 'Wellbeing'],
  },
  
  // Educational Leadership Jobs
  {
    id: 16,
    title: 'Headteacher',
    organization: 'Oakwood Primary School',
    location: 'Norwich, UK',
    type: 'Full-time',
    posted: '2023-07-01',
    match: 68,
    salary: '£65,000 - £80,000',
    applicationDeadline: '2023-09-15',
    startDate: 'January 2024',
    description: 'Inspirational Headteacher required to lead our successful primary school. The successful candidate will provide strategic vision, ensure outstanding teaching and learning, and maintain our strong community relationships.',
    aboutOrganization: 'Oakwood Primary is a two-form entry school with 420 pupils serving a diverse community. The school was rated Good with Outstanding features in its last Ofsted inspection.',
    responsibilities: [
      'Provide strategic leadership and vision',
      'Ensure high quality teaching and learning',
      'Manage school resources and budget',
      'Lead and develop staff team',
      'Maintain relationships with parents and community',
    ],
    requirements: [
      { id: 1, text: 'Qualified Teacher Status', essential: true, met: true },
      { id: 2, text: 'National Professional Qualification for Headship', essential: true, met: false },
      { id: 3, text: 'Successful leadership experience as Deputy Head', essential: true, met: true },
      { id: 4, text: 'Evidence of school improvement impact', essential: true, met: true },
      { id: 5, text: 'Financial management experience', essential: true, met: false },
    ],
    benefits: [
      'Leadership salary scale',
      'Relocation package available',
      'Dedicated leadership development',
      'Supportive governing body',
      'Well-resourced school environment',
    ],
    applicationProcess: 'Two-day assessment including panel interviews, presentation to governors, in-tray exercise, and meeting with school council. School visits encouraged prior to application.',
    category: 'Educational Leadership',
    skills: ['School Leadership', 'Strategic Planning', 'Staff Management', 'Community Engagement'],
  },
  {
    id: 17,
    title: 'Director of Education',
    organization: 'Brightside Learning Trust',
    location: 'Bristol, UK',
    type: 'Full-time',
    posted: '2023-07-05',
    match: 82,
    salary: '£75,000 - £90,000',
    applicationDeadline: '2023-09-30',
    startDate: 'January 2024',
    description: 'Strategic education leader required to oversee teaching, learning and school improvement across our growing multi-academy trust. The successful candidate will ensure high standards across all academies and lead our expansion plans.',
    aboutOrganization: 'Brightside Learning Trust currently manages six primary and three secondary academies across the Southwest region, with plans to expand to 15 schools in the next three years.',
    responsibilities: [
      'Lead educational strategy across the trust',
      'Monitor and improve standards in all academies',
      'Oversee school improvement partners',
      'Develop leadership capacity across schools',
      'Represent the trust with external stakeholders',
    ],
    requirements: [
      { id: 1, text: 'Qualified Teacher Status', essential: true, met: true },
      { id: 2, text: 'Successful headship experience', essential: true, met: true },
      { id: 3, text: 'Multi-academy trust experience', essential: true, met: true },
      { id: 4, text: 'Track record of school improvement', essential: true, met: true },
      { id: 5, text: 'Experience of Ofsted inspections', essential: true, met: true },
      { id: 6, text: 'Master\'s degree in education', essential: false, met: true },
    ],
    benefits: [
      'Executive level salary',
      'Performance-related bonus',
      'Company car allowance',
      'Pension contribution of 15%',
      'Private healthcare',
    ],
    applicationProcess: 'Comprehensive selection process including initial interview, assessment center, and final panel interview with trustees. Applications should include detailed CV and statement addressing selection criteria.',
    category: 'Educational Leadership',
    skills: ['Multi-Academy Leadership', 'School Improvement', 'Strategic Planning', 'Stakeholder Management'],
  },
  {
    id: 18,
    title: 'Early Years Foundation Stage Leader',
    organization: 'Bright Horizons Children\'s Centers',
    location: 'Reading, UK',
    type: 'Full-time',
    posted: '2023-07-18',
    match: 91,
    salary: '£32,000 - £38,000',
    applicationDeadline: '2023-08-31',
    startDate: 'October 2023',
    description: 'Experienced Early Years Leader required to oversee our EYFS provision across multiple nursery settings. The successful candidate will ensure high-quality early education, staff development, and statutory compliance.',
    aboutOrganization: 'Bright Horizons operates premium childcare centers across the UK, with five settings in the Reading area serving children from 3 months to 5 years of age.',
    responsibilities: [
      'Lead pedagogical approach across multiple settings',
      'Monitor and ensure EYFS framework compliance',
      'Coach and develop early years practitioners',
      'Manage relationships with parents and external partners',
      'Implement quality improvement initiatives',
    ],
    requirements: [
      { id: 1, text: 'Level 6 qualification in Early Childhood', essential: true, met: true },
      { id: 2, text: 'Minimum 3 years leadership experience in early years', essential: true, met: true },
      { id: 3, text: 'Deep understanding of EYFS curriculum', essential: true, met: true },
      { id: 4, text: 'Experience mentoring and developing staff', essential: true, met: true },
      { id: 5, text: 'Knowledge of Ofsted inspection framework', essential: true, met: true },
    ],
    benefits: [
      'Competitive salary package',
      'Leadership development program',
      'Childcare discount for own children',
      'Enhanced pension contribution',
      'Wellbeing support services',
    ],
    applicationProcess: 'Apply with CV and detailed covering letter. Interview process includes presentation on early years vision, practical observation assessment, and panel interview.',
    category: 'Educational Leadership',
    skills: ['Early Years Education', 'Staff Development', 'Quality Assurance', 'Parent Partnership'],
  },
  
  // Other Education Roles
  {
    id: 19,
    title: 'Education Technology Specialist',
    organization: 'Future Learn Educational Solutions',
    location: 'Cambridge, UK',
    type: 'Full-time',
    posted: '2023-07-14',
    match: 84,
    salary: '£35,000 - £45,000',
    applicationDeadline: '2023-08-30',
    startDate: 'September 2023',
    description: 'Innovative EdTech Specialist required to support schools in implementing digital learning solutions. The role involves training teachers, advising on technology integration, and developing digital resources.',
    aboutOrganization: 'Future Learn partners with over 200 schools nationwide to enhance teaching and learning through effective use of educational technology and digital resources.',
    responsibilities: [
      'Deliver professional development on educational technology',
      'Consult with schools on digital strategy',
      'Create engaging digital learning resources',
      'Support implementation of learning platforms',
      'Evaluate impact of technology solutions',
    ],
    requirements: [
      { id: 1, text: 'Teaching qualification or equivalent experience', essential: true, met: true },
      { id: 2, text: 'Advanced digital skills and technology knowledge', essential: true, met: true },
      { id: 3, text: 'Experience delivering teacher training', essential: true, met: false },
      { id: 4, text: 'Knowledge of learning platforms and digital tools', essential: true, met: true },
      { id: 5, text: 'Understanding of curriculum integration', essential: true, met: true },
    ],
    benefits: [
      'Hybrid working model',
      'Latest technology equipment',
      'Professional development budget',
      'Flexible working hours',
      'Performance bonuses',
    ],
    applicationProcess: 'Submit application with digital portfolio demonstrating EdTech projects. Interview includes presentation on technology integration and practical demonstration of digital skills.',
    category: 'Educational Technology',
    skills: ['Digital Learning', 'Teacher Training', 'Learning Platforms', 'Resource Development'],
  },
  {
    id: 20,
    title: 'School Improvement Advisor',
    organization: 'Education Excellence Partners',
    location: 'National (UK)',
    type: 'Full-time',
    posted: '2023-07-08',
    match: 70,
    salary: '£55,000 - £65,000',
    applicationDeadline: '2023-09-15',
    startDate: 'October 2023',
    description: 'Experienced School Improvement Professional required to work with partner schools on raising standards and addressing improvement priorities. The role involves school evaluation, leadership coaching, and implementing change strategies.',
    aboutOrganization: 'Education Excellence Partners is a leading school improvement consultancy working with schools across England to drive sustainable improvement and prepare for Ofsted inspections.',
    responsibilities: [
      'Conduct school reviews and quality audits',
      'Coach senior leaders on improvement strategies',
      'Develop action plans addressing identified priorities',
      'Deliver targeted training to staff teams',
      'Monitor impact of improvement interventions',
    ],
    requirements: [
      { id: 1, text: 'Successful senior leadership experience', essential: true, met: true },
      { id: 2, text: 'School inspection or improvement experience', essential: true, met: false },
      { id: 3, text: 'Track record of school improvement impact', essential: true, met: true },
      { id: 4, text: 'Strong knowledge of education policy', essential: true, met: true },
      { id: 5, text: 'Coaching qualification', essential: false, met: true },
    ],
    benefits: [
      'Competitive consultancy package',
      'Company car or allowance',
      'Flexible/remote working options',
      'Professional development fund',
      'Performance-related bonuses',
    ],
    applicationProcess: 'Submit comprehensive CV with evidence of improvement impact and detailed covering letter. Selection process includes case study presentation and panel interview.',
    category: 'Educational Consultancy',
    skills: ['School Evaluation', 'Leadership Coaching', 'Change Management', 'Quality Assurance'],
  }
];

export default enhancedJobData; 